
- name: Setup PostgreSQL
  hosts: all

  pre_tasks:
    - name: "Ensure stopped nginx"
      service:
        name: nginx
        state: stopped
        enabled: false
      ignore_errors: yes

  roles:
    - role: geerlingguy.postgresql
      tags: postgresql
    - role: geerlingguy.apache
      tags: apache
    - role: geerlingguy.php
      tags: php
    - role: local.adminer
      tags: adminer

